In [1]:
#Command to install numpy

!pip install numpy

In [2]:
#importing numpy
import numpy as np

In [3]:
#creating arrays in numpy
my_array = np.array([1,2,3,4,5])
print(my_array)
print("Type of this array: ",type(my_array))

[1 2 3 4 5]
Type of this array:  <class 'numpy.ndarray'>


In [4]:
#1-D array
array1D = np.array([1,2,3,4,5])
print(array1D)
print("Shape of this array: ",array1D.shape)

[1 2 3 4 5]
Shape of this array:  (5,)


In [5]:
#2-D array
array2D = np.array([(1,2,3,4),(4,5,6,8)])
print(array2D)
print("Shape of this array: ", array2D.shape)

[[1 2 3 4]
 [4 5 6 8]]
Shape of this array:  (2, 4)


In [6]:
#converting array from one datatype to another
#by default datatype in numpy arrays are int
new_Arr = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(new_Arr)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [7]:
#Initializing an array with all values as zero
zero_arr = np.zeros((3,4))      #needs to mention the shape 
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#Intializing an array with all values as one
ones_arr = np.ones((3,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#Initializing an array with particular value
arr_X = np.full((3,2), 8)   #setting value 8 
print(arr_X)

[[8 8]
 [8 8]
 [8 8]]


In [10]:
#Creating an Identity matrix
identity_arr = np.eye(4)
print(identity_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Creating an array with random values
random_arr = np.random.random((3,4))  #all the random values lies between 0 and 1
print(random_arr)

[[0.2973809  0.42434402 0.88588524 0.56700405]
 [0.49578398 0.15852888 0.77089542 0.04425438]
 [0.62078715 0.53374699 0.06023498 0.49704452]]


In [12]:
#Creating an array with random values , but with integer type
random_int_arr = np.random.randint(10,100,(3,4))     #random int values from 10 to 100
print(random_int_arr)

[[40 40 27 26]
 [30 29 98 89]
 [27 54 59 88]]


In [13]:
#Evenly spaced value array --> specifying the number of values required
evenly_spaced = np.linspace(10,40,7)   #spacing from 10 to 40 , and array will have 7 value with equal space
print(evenly_spaced)

[10. 15. 20. 25. 30. 35. 40.]


In [14]:
#Evenly spaced value array --> specifying the number of steps required
step_evenly_spaced = np.arange(10,40,7)  #here 7 is steps
print(step_evenly_spaced)

[10 17 24 31 38]


In [15]:
#Converting a list into numpy array
list_1 = [10,20,30,40,50]
into_array = np.asarray(list_1)
print(into_array)
type(into_array)

[10 20 30 40 50]


numpy.ndarray

In [16]:
#Creating an numpy array for analysis
test_arr = np.random.randint(10,90,(5,5))
print(test_arr)

[[53 21 46 82 79]
 [76 62 76 33 18]
 [73 48 16 77 12]
 [13 63 41 22 86]
 [63 84 38 46 52]]


In [17]:
#array dimension
test_arr.shape

(5, 5)

In [18]:
#number of dimensions
test_arr.ndim

2

In [19]:
#number of elements present in an array
test_arr.size

25

In [20]:
#cheking the datatype in array
test_arr.dtype

dtype('int32')

In [22]:
arr1 = np.random.randint(0,10,(2,2))
arr2 = np.random.randint(11,20,(2,2))
print("Addition: \n",arr1+arr2)
print("Subtraction: \n",arr1-arr2)
print("Multiplication: \n",arr1*arr2)
print("Division: \n" ,arr1/arr2)

Addition: 
 [[28 20]
 [21 18]]
Subtraction: 
 [[-10 -16]
 [ -5 -16]]
Multiplication: 
 [[171  36]
 [104  17]]
Division: 
 [[0.47368421 0.11111111]
 [0.61538462 0.05882353]]


In [24]:
#through numpy function
print("Numpy Addition: \n",np.add(arr1,arr2))
print("NUmpy Subtraction: \n",np.subtract(arr1,arr2))
print("Numpy Multiplication: \n",np.multiply(arr1,arr2))
print("Numpy Division: \n" ,np.divide(arr1,arr2))

Numpy Addition: 
 [[28 20]
 [21 18]]
NUmpy Subtraction: 
 [[-10 -16]
 [ -5 -16]]
Numpy Multiplication: 
 [[171  36]
 [104  17]]
Numpy Division: 
 [[0.47368421 0.11111111]
 [0.61538462 0.05882353]]


In [27]:
#Transpose of a array
arr3 = np.random.randint(10,30,(3,4))
print("Before transpose: \n",arr3)
print("Shape before transpose: ",arr3.shape)

print("After Transpose : \n",np.transpose(arr3))
print("Shape after transpose: ",arr3.shape)

Before transpose: 
 [[17 10 26 18]
 [17 17 20 15]
 [11 29 29 29]]
Shape before transpose:  (3, 4)
After Transpose : 
 [[17 17 11]
 [10 17 29]
 [26 20 29]
 [18 15 29]]
Shape after transpose:  (3, 4)


In [29]:
#Transpose using .T function
arr4 = np.random.randint(10,30,(3,4))
print("Before transpose: \n",arr4)
print("Shape before transpose: ",arr4.shape)

trans = arr3.T
print("After Transpose : \n",trans)
print("Shape after transpose: ",trans.shape)

Before transpose: 
 [[15 11 10 15]
 [15 29 29 14]
 [16 16 17 25]]
Shape before transpose:  (3, 4)
After Transpose : 
 [[17 17 11]
 [10 17 29]
 [26 20 29]
 [18 15 29]]
Shape after transpose:  (4, 3)


In [ ]:
#Reshaping an numpy array
arr_A = np.random.randint(0,10,(2,3))
print("Array A :-> ",arr_A)

arr_B = arr_A.reshape((3,2))
print("Reshaped array:-> ",a